### ISSUE TITLE
能上传一下requirements.txt 吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [qmpzzpmq/aec3_raaec#1]
我用的环境跑这个工程有很多地方报错 pytorch 和 hydra 都有，能上传一下你的requirements.txt，谢谢！

**Comment by qmpzzpmq** [comment]
这个项目已经不太维护了 谢谢

**Comment by zuowanbushiwo** [comment]
我靠，神速啊，还没反应过来就关闭了，我还以为我没提交成功了。
作为一个还没入门的小白，觉得这个工程还挺好的，我觉得效果应该也还不错啊。

**Comment by qmpzzpmq** [comment]
效果十分辣鸡， 有兴趣看看aec3 和 torch怎么打通就行了

**Comment by zuowanbushiwo** [comment]
好，谢谢！
